services:
  - type: web
    name: jainova-website
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false