export const ProductData = {
	Parenterals: [
		{ text: "Aciclovir for Injection USP 250 mg / vial, 500 mg / vial, 1g/vial" },
		{ text: "Amphotericin-B for Injection USP 50 mg/vial & 100mg/vial" },
		{ text: "Azithromycin for Injection 500 mg/vial" },
		{ text: "Clarithromycin for injection 500 mg/vial" },
		{ text: "Dobutamine for Injection USP 250 mg / vial, 50mg/ml" },
		{ text: "Adrenaline Injection BP 1 mg / ml" },
		{ text: "Esomeprazole Sodium Powder for Injection 40 mg / vial, 20mg/vial" },
		{ text: "Ganciclovir for Injection 500 mg" },
		{ text: "Hydralazine for Injection 20 mg / ampoule or vial" },
		{ text: "Indomethacin for Injection 1 mg/vial" },
		{ text: "Ketoprofen for Injection 100 mg/ampoule or vial" },
		{ text: "Lornoxicam for Injection 8 mg/vial" },
		{ text: "Nicorandil for Injection 2 mg/vial, 48 mg/vial" },
		{ text: "Olanzapine Injection 10 mg/vial" },
		{ text: "Omeprazole for injection 40 mg / vial ," },
		{ text: "Pantoprazole for Injection 40 mg / vial" },
		{ text: "Pralidoxine Chloride for Injection 500 mg / vial, 1 gm / vial" },
		{ text: "Rabeprazole Sodium for Injection 20 mg / vial" },
		{ text: "Succinylcholine Chloride for Injection USP 100 mg / vial, 500 mg / vial" },
		{ text: "Vancomycin Hydrochloride Sterile for Injection USP 500 mg / vial, 1 gm / vial" },
		{ text: "Vecuronium Bromide for Injection 4 mg/ampoule or vial, 10mg/vial" },
		{ text: "Voriconazole for Injection 200 mg / vial" },
		{ text: "Acetazolamide injection 500mg/vial" },
		{ text: "Caspofungin injection 50mg/vial , 70mg/vial" },
		{ text: "Colistimethate injection 100,000 IU/vial , 200,000 IU/vial" },
		{ text: "Lansoprazole injection 30mg/vial" },
		{ text: "Rifampicin injection 600mg/vial" },
		{ text: "Thiopental Injection 500mg/vial , 1gm/vial" },
		{ text: "Zoledronic injection4mg/5ml" },
		{ text: "Allopurinol sodium for injection 500mg/vial" },
	]
};